export type ActLibraryItem = {
  id: string;
  title: string;
  year: number;
  category: string;
  jurisdiction: string;
  pdfModule: number;
};

export const ACTS_LIBRARY: readonly ActLibraryItem[] = [
  {
    id: "anti-money-laundering-act-2010",
    title: "Anti-Money Laundering Act",
    year: 2010,
    category: "Financial Crime",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/anti-money-laundering-act-2010.pdf"),
  },
  {
    id: "pakistan-penal-code",
    title: "Pakistan Penal Code",
    year: 1860,
    category: "Criminal Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/pakistan-penal-code.pdf"),
  },
  {
    id: "anti-narcotics-force-act-1997",
    title: "Anti Narcotics Force Act",
    year: 1997,
    category: "Criminal Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/anti-narcotics-force-act-1997.pdf"),
  },
  {
    id: "anti-rape-investigation-and-trial-act-2021",
    title: "Anti-Rape (Investigation and Trial) Act",
    year: 2021,
    category: "Criminal Procedure",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/anti-rape-investigation-and-trial-act-2021.pdf"),
  },
  {
    id: "anti-terrorism-act-1997",
    title: "Anti-Terrorism Act",
    year: 1997,
    category: "Criminal Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/anti-terrorism-act-1997.pdf"),
  },
  {
    id: "arbitration-international-investment-disputes-act-2011",
    title: "Arbitration (International Investment Disputes) Act",
    year: 2011,
    category: "Arbitration",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/arbitration-international-investment-disputes-act-2011.pdf"),
  },
  {
    id: "arbitration-act-1940",
    title: "Arbitration Act",
    year: 1940,
    category: "Arbitration",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/arbitration-act-1940.pdf"),
  },
  {
    id: "banking-companies-ordinance-1962",
    title: "Banking Companies Ordinance",
    year: 1962,
    category: "Banking",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/banking-companies-ordinance-1962.pdf"),
  },
  {
    id: "code-of-civil-procedure-1908",
    title: "Code of Civil Procedure",
    year: 1908,
    category: "Civil Procedure",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/code-of-civil-procedure-1908.pdf"),
  },
  {
    id: "code-of-criminal-procedure-1898",
    title: "Code of Criminal Procedure",
    year: 1898,
    category: "Criminal Procedure",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/code-of-criminal-procedure-1898.pdf"),
  },
  {
    id: "constitution-of-pakistan",
    title: "Constitution of the Islamic Republic of Pakistan",
    year: 1973,
    category: "Constitutional Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/constitution-of-pakistan.pdf"),
  },
  {
    id: "contract-act-1872",
    title: "Contract Act",
    year: 1872,
    category: "Civil Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/contract-act-1872.pdf"),
  },
  {
    id: "court-fees-act-1870",
    title: "Court-Fees Act",
    year: 1870,
    category: "Court Procedure",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/court-fees-act-1870.pdf"),
  },
  {
    id: "criminal-law-amendment-special-court-act-1976",
    title: "Criminal Law Amendment (Special Court) Act",
    year: 1976,
    category: "Criminal Procedure",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/criminal-law-amendment-special-court-act-1976.pdf"),
  },
  {
    id: "criminal-law-amendment-act-1908",
    title: "Criminal Law Amendment Act",
    year: 1908,
    category: "Criminal Procedure",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/criminal-law-amendment-act-1908.pdf"),
  },
  {
    id: "defamation-ordinance-2002",
    title: "Defamation Ordinance",
    year: 2002,
    category: "Civil Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/defamation-ordinance-2002.pdf"),
  },
  {
    id: "dissolution-of-muslim-marriages-act-1939",
    title: "Dissolution of Muslim Marriages Act",
    year: 1939,
    category: "Family Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/dissolution-of-muslim-marriages-act-1939.pdf"),
  },
  {
    id: "domestic-violence-prevention-protection-act-2026",
    title: "Domestic Violence (Prevention and Protection) Act",
    year: 2026,
    category: "Family Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/domestic-violence-prevention-protection-act-2026.pdf"),
  },
  {
    id: "easements-act-1882",
    title: "Easements Act",
    year: 1882,
    category: "Property Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/easements-act-1882.pdf"),
  },
  {
    id: "partnership-act-1932",
    title: "Partnership Act",
    year: 1932,
    category: "Business Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/partnership-act-1932.pdf"),
  },
  {
    id: "qanun-e-shahadat-1984",
    title: "Qanun-e-Shahadat",
    year: 1984,
    category: "Evidence Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/qanun-e-shahadat-1984.pdf"),
  },
  {
    id: "sale-of-goods-act-1930",
    title: "Sale of Goods Act",
    year: 1930,
    category: "Commercial Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/sale-of-goods-act-1930.pdf"),
  },
  {
    id: "secp-act-1997",
    title: "Securities and Exchange Commission of Pakistan Act",
    year: 1997,
    category: "Corporate Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/secp-act-1997.pdf"),
  },
  {
    id: "stamp-act-1899",
    title: "Stamp Act",
    year: 1899,
    category: "Revenue Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/stamp-act-1899.pdf"),
  },
  {
    id: "transfer-of-property-act-1882",
    title: "Transfer of Property Act",
    year: 1882,
    category: "Property Law",
    jurisdiction: "Pakistan",
    pdfModule: require("../assets/laws/transfer-of-property-act-1882.pdf"),
  },
];
